### PR TITLE
Testing installation

### PR DESCRIPTION
**Pull request by smasoka**
Removed a comment

### CODE REVIEW

**Comment by smasoka** [comment]
okay there are conflits

**Comment by smasoka** [comment]
mine was outdated, deleted it.

**Comment by brucellino** [comment]
Can you be a bit more specific please 

> mine was outdated
> your what ?

**Comment by brucellino** [comment]
I'm going to reject this because it doesn't add anything (just a few lines removed). However, the build error is still showing up in  build #297 - but I think this is a problem with GCC itself.

**Pull request closed without merging**
